/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KitFormCodecSelect: typeof import('./src/components/KitForm/KitFormCodecSelect.vue')['default']
    KitFormModeSelect: typeof import('./src/components/KitForm/KitFormModeSelect.vue')['default']
    KitFormOutput: typeof import('./src/components/KitForm/KitFormOutput.vue')['default']
    KitFormTextArea: typeof import('./src/components/KitForm/KitFormTextArea.vue')['default']
    KitMenu: typeof import('./src/components/KitMenu/KitMenu.vue')['default']
    KitMenuGroup: typeof import('./src/components/KitMenu/KitMenuGroup.vue')['default']
    KitMenuItem: typeof import('./src/components/KitMenu/KitMenuItem.vue')['default']
    Md5: typeof import('./src/components/Hash/md5.vue')['default']
    MD5: typeof import('./src/components/Hash/MD5.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheKitMenu: typeof import('./src/components/TheKitMenu.vue')['default']
  }
}
