/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KitBaseFormCodecSelect: typeof import('./src/components/KitForm/KitBaseFormCodecSelect.vue')['default']
    KitBaseFormSelect: typeof import('./src/components/KitForm/KitBaseFormSelect.vue')['default']
    KitFormControl: typeof import('./src/components/KitForm/KitFormControl.vue')['default']
    KitFormInput: typeof import('./src/components/KitForm/KitFormInput.vue')['default']
    KitFormInputArray: typeof import('./src/components/KitForm/KitFormInputArray.vue')['default']
    KitFormInputWithCodec: typeof import('./src/components/KitForm/KitFormInputWithCodec.vue')['default']
    KitFormModeConfig: typeof import('./src/components/KitForm/KitFormModeConfig.vue')['default']
    KitFormModeSelect: typeof import('./src/components/KitForm/KitFormModeSelect.vue')['default']
    KitFormPaddingSelect: typeof import('./src/components/KitForm/KitFormPaddingSelect.vue')['default']
    KitFormTextAreaWithCodec: typeof import('./src/components/KitForm/KitFormTextAreaWithCodec.vue')['default']
    KitMenu: typeof import('./src/components/KitMenu/KitMenu.vue')['default']
    KitMenuGroup: typeof import('./src/components/KitMenu/KitMenuGroup.vue')['default']
    KitMenuItem: typeof import('./src/components/KitMenu/KitMenuItem.vue')['default']
    KitRefLink: typeof import('./src/components/KitRefLink.vue')['default']
    KitStat: typeof import('./src/components/KitStat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheKitMenu: typeof import('./src/components/TheKitMenu.vue')['default']
  }
}
